name_prefix                              = "Pitfall"
domain                                   = "babosbird.com"
kubernetes_version                       = "1.28.3"  
ssh_public_key                           = "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vm_enabled                               = true
location                                 = "northeurope"
admin_group_object_ids                   = ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
web_app_routing_enabled                  = true
dns_zone_name                            = null
dns_zone_resource_group_name             = null
grafana_admin_user_object_id             = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vnet_integration_enabled                 = true
crossplane_provider_packages             = ["xpkg.upbound.io/upbound/provider-azure:v0.42.0"]
openai_enabled                           = false