name_prefix                              = "Pitfall"
domain                                   = "babosbird.com"
kubernetes_version                       = "1.28.3"  
ssh_public_key                           = "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vm_enabled                               = true
location                                 = "northeurope"
admin_group_object_ids                   = ["4e4d0501-e693-4f3e-965b-5bec6c410c03"]
web_app_routing_enabled                  = true
dns_zone_name                            = null
dns_zone_resource_group_name             = null
grafana_admin_user_object_id             = "0c5267b2-01f3-4a59-970e-0d9218d5412e"
vnet_integration_enabled                 = true
crossplane_provider_packages             = ["xpkg.upbound.io/upbound/provider-azure:v0.42.0"]
openai_enabled                           = false